#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
sketchybar --bar position=top \
                 height=40 \
                 blur_radius=30 \
                 color=0xCCbf7449 \
		 topmost=true

##### Changing Defaults #####
# Default values applied to all further items.
default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
SPACE_ICONS=("" "" "" "" "" "6" "7" "8" "9" "10")
SPACE_LABELS=("Code" "Web" "Social" "Media" "Other" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    label="${SPACE_LABELS[i]}"
    label.padding_left=-15
    label.padding_right=10
    icon="${SPACE_ICONS[i]}"
    icon.color=0x00BD4720
    icon.padding_left=0
    icon.font.size=18
    background.corner_radius=5
    background.height=30
    background.color=0x00ab3b16
    script="$PLUGIN_DIR/space.sh"
    click_script="/usr/local/bin/yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left \
             --set space."$sid" "${space[@]}" \
             --subscribe space."$sid" space_change
done

##### Adding Left Items #####
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####

# Clock
sketchybar --add item clock right \
           --set clock update_freq=10 \
                       script="$PLUGIN_DIR/clock.sh" \
		       icon.padding_left=0 \
		       icon.padding_right=0

sketchybar --add item spacer right \
           --set spacer background.drawing=off width=10

# Volume Item
sketchybar --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change

# Battery Item
sketchybar --add item battery right \
           --set battery update_freq=120 \
                         script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

# Shared Bracket for Volume and Battery
sketchybar --add bracket status_bracket volume battery \
           --set status_bracket background.color=0xFFBD4720 \
                               background.corner_radius=5 \
                               background.height=26 

# Singular Bracket for Clock 
sketchybar --add bracket time_bracket clock \
           --set time_bracket background.color=0xFFBD4720 \
                              background.corner_radius=5 \
                              background.height=26 \

##### Force all scripts to run the first time #####
sketchybar --update
